config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :students

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :make_header, :make_link

  def make_header(text)
    "<h1>#{text}</h1>".html_safe
  end

  def make_link(text, path)
    # '<a href="/students/2">terrance</a>'
    if path.is_a? String
      "<a href='#{path}'>#{text}</a>".html_safe
    else
      "<a href='/#{path.class.to_s.downcase.pluralize}/#{path.id}'>#{text}</a>".html_safe
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def show
    @student = Student.find_by(id: params[:id])
  end

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    student = Student.create(student_params)
    redirect_to(student)
  end

  def edit
    @student = Student.find_by(id: params[:id])
  end

  def update
    student = Student.find_by(id: params[:id])
    student.update(student_params)

    redirect_to student
  end


  def destroy
    @student = Student.find_by(id: params[:id])
    @student.destroy
    redirect_to students_path
  end



  private

  def student_params
    params.require(:student).permit(:name, :email, :dob)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentLister</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <%= f.text_field :name %>

  <%= f.text_field :email %>
  <%= f.submit %>
<% end %>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<h1>All the Students</h1>


<ul>
  <% @students.each do |student| %>
    <li><%= make_link(student.name, student) %> | <%= link_to 'Edit this student', edit_student_path(student) %></li>
  <% end %>
</ul>

<%= make_link 'See all the students', '/students' %>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<%= make_header(@student.name) %>
<p><%= @student.email %></p>

<p></p>

<%= make_link('See all the students', students_path) %>
<%= link_to 'Delete this student', student_path(@student), {method: 'DELETE', class:'my-link'} %>